server:
  port: 8080
spring:
  application:
    #应用的名称，可选
    name: reggie-take_out
  datasource:
      url: jdbc:mysql://localhost:3306/reggie
      driverClassName: com.mysql.cj.jdbc.Driver
      username: root
      password:
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
reggie:
  path: C:\Users\User\Desktop\book\img\